### ISSUE TITLE
no "et al." when citing from multiple authors

### ISSUE THREAD

**Issue by henczati** [michal-h21/biblatex-iso690#12] opened 2015-05-05 16:41 UTC
Hi!

Why do you think that when I `\cite` an entry from multiple authors, only the first author is listed and there is no "et al." following.
Could this be a bug, or is there some biblatex/biber configuration I'm missing?
I read that setting the `mincitenames` and `maxcitenames` biblatex options to 1 should help, but it had no results whatsoever.

Also, the author's name is cited "Surname, Firstname", which I think is unusual if not using `\parencite`.

I'm a beginner to LaTeX and this is the very first time I tried my luck with biblatex/biber, so probably it is me doing it wrong.

Good job with the package, thank you for creating it.

**Comment by johannesbottcher** [comment] 2015-05-05 18:00
```tex 
\listfiles
\documentclass[english]{article}
\usepackage{babel}
\usepackage[
  ,style=iso-authoryear
]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
\cite{companion}
\printbibliography
\end{document}
```

Assuming the above example, we can see the behaviour. Using Lastname, (comma) fisrstname  and omiting the *et al.* is defined within the `iso-authoryear` citation style. So, no i wouldn't say that this is a bug. I don't have the ISO690 at hand, so i cannot check if they make the recommendation.

**Comment by henczati** [comment] 2015-05-05 18:41
Hi, thanks for the fast reply.

I also checked out another project aiming at implementing the ČSN ISO 690 and 690-2 standard (the Czech translation) as a `bibtex` style (http://repo.or.cz/w/csplainnat.git), and I'm fairly convinced that they are adding *et al.*.  Unfortunately, that project is Czech-only, and the generated bibliography contains Czech phrases and abbreviations.  Thing is, I'm in the Czech Republic, so I *have to* comply with ISO 690, but I am writing in English.

I just searched and found a Czech document from 2008 detailing how to cite and structure bibliography entries using the international ISO 690 and 690-2 standards: http://www.evskp.cz/SD/4c.pdf
I don't know if it helps *you* specifically, but I understand that the owner of this repo is Czech himself.
The first match of "et al." on the bottom of page 8 says (in loose translation; my Czech is not the best), that if there are 3 or more authors of a document, it is allowed to cite only the surname of the first one and add "et al." (or it's Czech equivalent) if it would not result in ambiguity in identifying the source.

**Comment by johannesbottcher** [comment] 2015-05-05 18:56
Quoting ISO 690:  
>For works with four or more creators, all names should be given if possible. If any names are omited, the name of the creator shall be givven followed by "and others" or "et al.".

>EXAMPLE FITTING, Hans and others


So i guess the `andothers`-string should really be there. Let's wait for Michals input. I'll have a look at this later.

**Comment by henczati** [comment] 2015-05-06 17:31
Hi again,
I noticed that the pdf I linked before is deprecated now. Since its release, ISO 690:2010 came out, and to match it in Czech, CSN ISO 690:2011.

On this page, there are links for Czech sources explaining the new standard:
https://ezdroje.muni.cz/prehled/zdroj.php?lang=cs&id=441

The inverted form of the first author's name seems to be correct, but simply omitting the others is definitely not.
E.g. see (in Czech) this page https://sites.google.com/site/novaiso690/prvky-citace/tvuarce
or paragraph `g.` (in subsection `3.1.`) on page 10 in this document: http://www.citace.com/download/CSN-ISO-690.pdf

**Comment by johannesbottcher** [comment] 2015-05-06 17:36
I think the locale standards are really just localizations and the international ISO 690 applies. :-) 

The name is correct, leaving out *andothers* does not seem to be. The files are open, i just didn't came around to it yet. I fixed some of the other stuff though.

**Comment by henczati** [comment] 2015-05-06 17:43
Thank you, any improvement is appreciated. ;)

**Comment by johannesbottcher** [comment] 2015-05-11 21:36
There is quite a lot to do and the whole biblatex business is a bit messy for me. Right now, all the non fancy stuff is done by the standard styles. Supporting maps, and audio CDs and the *truncate if more than for authors* isn't supported. But the ISO prefers all to be written out anyway. I am still sitting over this.

**Comment by henczati** [comment] 2015-05-11 21:55
Well, I think all the authors appeared in the bibliography listing, but when cited, for me there was no indication of the other authors at all (only the full name of the first one).  I don't think this is a usable state.  Or could I have something misconfigured?

**Comment by johannesbottcher** [comment] 2015-05-11 22:08
The `iso` style is buggy here. A standard `authoryear` would be ok.

**Comment by michal-h21** [comment] 2015-06-03 09:48
biblatex-iso was created before new version of the norm was released, so I
was using

http://www.evskp.cz/SD/4c.pdf

as my source, because it was recommendation for Czech universities how to
cite. But it seems that et al. in citations should be really used.

Standard author-year citation style is included in the iso-authoryear, only
some macros are redefined, I think it was because of support of citation of
multiple books from the same author and year, so we support this: cite 1
(Somebody, 2014a), cite 2 (Somebody, 2014b). I think there must be some
option for this in standard Biblatex, so we can get rid of these custom
macros and use standard ones, but I must admit that Biblatex changed lot
recently and I don't understand it as much as I did few years ago. Do
Johannes know how to do that?



On Tue, May 12, 2015 at 12:08 AM, johannesbottcher <notifications@github.com

**Comment by johannesbottcher** [comment] 2015-06-03 14:01
@michal-h21 The standard styles take care of all that. Reading through the ISO, it seems that biblatex, few exceptions like music, takes care of everything mentioned. I wasn't able to find any reference to `urlavailable` and the like.<sup>1</sup> You can define a langid per entry, biblatex will use the bibliography strings for the current set language. Building on top of `standard.bbx` and `biblatex.def`  seems to be a very good and time-saving effort. 

<sup>1</sup> Can you give any reference for this?

MWE for the name stuff, adjustable via `uniquename`.
```latex
\documentclass{article}
\usepackage[style=authoryear]{biblatex}
\begin{filecontents}{\jobname.bib}
	@book{petera,
		author={peter parker},
		year={2014},
		title={sugar and spice and everything nice},
	}
	@book{peterb,
		author={peter parker},
		year={2014},
		title={no fancy title},
	}
	@book{peterc,
		author={Jack parker},
		year={2014},
		title={very fancy title},
	}
\end{filecontents}
\addbibresource{\jobname.bib}
\ExecuteBibliographyOptions{uniquename=init}
\begin{document}
\cite{petera} and \cite{peterb} and even \cite{peterc}
\printbibliography
\end{document}
```

**Comment by michal-h21** [comment] 2015-06-03 20:16
>
> michal-h21 <https://github.com/michal-h21> The standard styles take care
> of all that. Reading through the ISO, it seems that biblatex, few
> exceptions like music, takes care of everything mentioned. I wasn't able to
> find any reference to urlavailable and the like.1
>
The problem is that Czech interpretation of ISO is done by a professor of
library science and importance is put on some really strange details, which
are based on library cataloging. So we need to distinguish three
posibilities:

1. publication is published only online. in this case we use `url` string.
it is used when `urldate` field is set
2. publication is published in print, but there is also free online
version. Example of such publication are articles in Tugboat. We don't use
`urldate` field and `urlalso` string is used.
3. publication is published in print  and there is also online version
behind payval, such as Ebsco or Science Direct. In this case the comment
must be put in the `howpublished` field. `urlcomercial` bibliography string
is declared, but it is never used (and I know about the typo now)


> You can define a langid per entry, biblatex will use the bibliography
> strings for the current set language.
>
but the problem is that you must use both languages in one entry:

LYNCH, C. 2005. Where do we go from here?: the next decade for digital
libraries. DLib
Magazine [online]. 2005, vol. 11, no. 7/8 [cit. 2005-08-15]. Dostupný z WWW:
hhttp://www.dlib.org/dlib/july05/lynch/07lynch.htmli. ISSN 1082-9873.

This is a reference entry of an English article in Czech document. Journal
volume and number are in English, Url date and url info are in Czech. I
know that it is insane. This is why we have `\mainlstring` and
`\mainsstring` commands.


> Building on top of standard.bbx and biblatex.def seems to be a very good
> and time-saving effort.
>
obviously, we just must pay attention to these stupid details :(

The `mwe` seems to be nice, name should be just in the inverted format, but
we can obviously just set some parameters of standard citation style,
instead of some broken macros.

**Comment by johannesbottcher** [comment] 2015-06-03 21:52
>LYNCH, C. 2005. Where do we go from here?: the next decade for digital libraries. DLib Magazine [online]. 2005, vol. 11, no. 7/8 [cit. 2005-08-15]. Dostupný z WWW: hhttp://www.dlib.org/dlib/july05/lynch/07lynch.htmli. ISSN 1082-9873. 

How would a bib-entry look for this? It is in a magazine, so i think `article`?  But if only published online, `online`? 

```latex
%pseudo
@online{magentry,
	author={LYNCH, C.},
	year={2005},
	title={Where do we go from here?},
	subtitle={the next decade for digital libraries},
	journaltitle={DLib Magazine},
	volume={11},
	number={7/8},
	urldate={2005-08-15},
	url={http://www.dlib.org/dlib/july05/lynch/07lynch.htmli},
	issn={1082-9873},
	langid={english}
}
```

Now, my argumnt would be, if the online article was published in a well defined environment (issn, volumen, number, journal ...) and cannot change, it should be treated as an article, no matter if never printed. 
According to the  `biblatex` documentation, `article` would be preferred. But that would very much contradict with your first point you (or rather iso690-cz) were making. 



Ah, now i see it in the german and english ISO as well. Logically, the above would output something along the lines of *also available at www.something.org*, which would be wrong as it is the only place where to find the article. On the other hand, setting this as an `online`-entry would contradict the `biblatex` doc. Adding an extra field to denote the difference? `biblatex`  with all its internals is quite complex enough, but right now this seems to be the only way to get the field`[Online:]`.

If we define it as `online`, we would need to declare volume and number and journaltitle valid for `online` entries, could set them as they are and use the documents main language to set the `urlalso` and similar strings. Possible, but once more contradictory. 

It is quite late, and i think i'll think about this tomorrow once more. 


Would i

**Comment by henczati** [comment] 2015-07-19 22:10
Hi,
I pulled the latest master, and there is still no `et al.`, no other authors, only the first author's surname when using the `iso-authoryear` style.

Using the `authoryear` style as @johannesbottcher suggested makes it work seemingly correctly: for 5 authors I get `et al.`, for 3 their surnames get listed. However, with plain `authoryear` the surnames in the bibliography are not all-caps which will not work for me (I suspect it is missing other iso690 requirements, too).

How is it coming along? I would need this before the end of the month. If you don't have time to work on this now, please note. Thanks.

**Comment by henczati** [comment] 2015-07-19 22:40
Btw, `authoryear` is not without quirks either: for 3 authors I get a comma before the *and* but never before the date:

* `authoryear`:
    - `\cite`

     > First, Second, and Third 2015

    - `\textcite`

     > First, Second, and Third (2015)

    - `parencite`

     > (First, Second, and Third 2015)

* `iso-authoryear`:
    - `\cite`

     > First, 2015

    - `\textcite`

     > First, (2015)

    - `parencite`

     > (First, 2015)

**Comment by DavidLuptak** [comment] 2016-10-23 15:05
Implemented, closing.

**Closed by DavidLuptak** 2016-10-23 15:05 UTC
